FROM alpine:3.20

RUN adduser -D -u 10001 appuser
WORKDIR /home/appuser

RUN apk --no-cache add ca-certificates

COPY dist/api-go ./api-go
RUN chmod 755 ./api-go

USER 10001

EXPOSE 8080

CMD ["./api-go"]
