apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: focus-jitsi-stage
  namespace: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/qmish/Focus.git
    targetRevision: master
    path: k8s/jitsi-stage
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: jitsi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10
